### ISSUE TITLE
У меня не работает сборка "4ifir 1.6"

### ISSUE THREAD

**Issue by MadTooth** [rashevskyv/4IFIR#10]
После установки последней сборки "4ifir'а 1.6" система на загружается, при загрузке в "Atmosphere" происходит "ошибка" (для понимания: у меня кефир работает, 4ifir устанавливал и "так и сяк", результат никакой)
[report_0000000000b277ba.bin.txt](https://github.com/rashevskyv/4IFIR/files/12568150/report_0000000000b277ba.bin.txt)
![error](https://github.com/rashevskyv/4IFIR/assets/30464341/1776e258-596f-4e6e-88de-a73ae3b55143)

**Comment by rashevskyv** [comment]
Бо 1.6 не підтримує останню прошивку. Ставте 16.0.3 і все запрацює

нд, 10 вер. 2023 р., 15:05 користувач MadTooth ***@***.***>
пише:
