### ISSUE TITLE
What latest firmware version does 4ifir 1.7 support ?

### ISSUE THREAD

**Issue by MadTooth** [rashevskyv/4IFIR#11]
As always, nothing is written about the version of the supported firmware, I am accurate for everyone, so as not to waste time on useless console updates

**Comment by cagricolak** [comment]
i have latest firmware and 4sifir running perfect.

**Comment by rashevskyv** [comment]
16.1.0

пт, 29 вер. 2023 р., 22:39 користувач Çağrı ÇOLAK ***@***.***>
пише:

**Comment by Originalimoc** [comment]
Is 17.0.1 supported by 1.8?
