### ISSUE TITLE
Проблемы с FPSLocker 

### ISSUE THREAD

**Issue by judgementnyan** [rashevskyv/4IFIR#12]
![2023110914244400](https://github.com/rashevskyv/4IFIR/assets/150350105/537a7152-e81a-4cfb-a17f-89f0ae0528a4)
Такая проблема: SaltyNX is not working

**Comment by postcanonical** [comment]
Все вопросы в группу в телеграмме.

**Comment by saduwka** [comment]
Привет. Столкнулся с такой же проблемой, где можно найти эту группу телеграмм
