### ISSUE TITLE
Right Joycon Lagging and Randomly Disconnects when Docked

### ISSUE THREAD

**Issue by GloomySenpai** [rashevskyv/4IFIR#13]
What's the issue you encountered?
Recently, while playing on my Switch in docked mode, the right Joy-Con suddenly started lagging severely, making it practically unplayable. I've attempted various solutions – switching Joy-Cons, updating both the dock and Joy-Cons, and even testing another Switch in the same dock – but none proved effective.

System Firmware Version
16.1.10 / AMS 1.6.2 / E

Environment?
What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 6.0.7 
Official release or unofficial build: atmosphere 1.6.2-master
EmuMMC or SysNAND: EmuMMC partition-based.

I use 4IFIR

**Comment by matiasmercado-ar** [comment]
I got the same problem, right Joycon. This doesn't happen on docked mode OFW.

**Comment by postcanonical** [comment]
Ask your questions in telegram this is just a guide, nothing more.
