### ISSUE TITLE
Fatal Error sys-clk is not running

### ISSUE THREAD

**Issue by Xalex79** [rashevskyv/4IFIR#16]
When trying to use 4IFIR RatTest Overlay this error "Fatal Error sys-clk is not running". Tried the sys-clk 1.0.3 and 2.0.0-rc

**Comment by rashevskyv** [comment]
Toi should use only built-in sysclck

вт, 5 груд. 2023 р., 21:06 користувач Alejandro Rosado <
***@***.***> пише:

**Comment by rashdwhy** [comment]
Hello, I'm having the same problem with the 4ifir sys-clk, I have never changed the files from the 4ifir installation, please help.

**Comment by redstonetechwiz** [comment]
Having same issue as OP. Did not change any installation files. Seems to work in my 16.1.0 emummc but not 17.0.1 sysmmc

**Comment by rashdwhy** [comment]
I think I have found a solution, you must boot throught "atmosphere/package3" instead of "bootloader/payloads/fusee.bin", it might be a solution, or a problem once again, I hope it works out for everyone with the problem

**Comment by rashdwhy** [comment]
We just have to wait for the next update to come and support firmware version 17.0.1.

**Comment by rorosaurus** [comment]
Is there no workaround?

I downgraded to HOS16, and installed 4IFIR 1.9 beta from AOI updater. But I still have issues.

sys-clk is running fine, but 4IFIR RatTest still says sys-clk is not running. 4IFIR Wizard claims a kip mismatch.

Is this the correct version we should be downloading? I don't understand why it's not included or at least a link to the right repository and version? https://github.com/hanai3Bi/Switch-OC-Suite/releases

**Comment by rashdwhy** [comment]
What are the results of using "Switch OC Suite"?

Does it work after that?

**Comment by rafraleo** [comment]
I just installed 4IFIR and now i'm happy not beeing the only one to have this issue...

Sys-clk was running well when I was only on KEIFR, but now it says that is not running...

I'm on firmware 17.0

**Comment by rashevskyv** [comment]
4ifir is not support 17.x.x
