### ISSUE TITLE
Erista 1113 MHz voltage

### ISSUE THREAD

**Issue by saaaaaaaaaaaaaaaaaas** [rashevskyv/4IFIR#17]
Could you please add less voltage for 1113 Mz gpu clock speed on Erista models? 1050mV is too high and 3 of 3 Eristas that tested this voltage works completely fine. 990mV and higher vould be great. Also could you add 3 more gpu steps for Erista with bigger list of voltages to pick up? (1152 MHz, 1190 MHz, 1228 Mhz)

**Comment by Cooler3Ds** [comment]
> Could you please add less voltage for 1113 Mz gpu clock speed on Erista models? 1050mV is too high and 3 of 3 Eristas that tested this voltage works completely fine. 990mV and higher vould be great. Also could you add 3 more gpu steps for Erista with bigger list of voltages to pick up? (1152 MHz, 1190 MHz, 1228 Mhz)

Sorry, I noticed your request too late.
It looks like your request has already been granted in the upcoming update.
Thanks for your feedback.
Let me know if I can help you with anything else.

```
.eristaGpuDvfsTable = {
	// Freq KHz  	// Volt uV
	//{  192000, {}, {  687500, } },
	{  230400, {}, {  687500, } },
	{  268800, {}, {  700000, } },
	{  307200, {}, {  712500, } },
	{  345600, {}, {  725000, } },
	{  384000, {}, {  737500, } },
	{  422400, {}, {  750000, } },
	{  460800, {}, {  762500, } },
	{  499200, {}, {  775000, } },
	{  537600, {}, {  787500, } },
	{  576000, {}, {  800000, } },
	{  613400, {}, {  812500, } },
	{  652800, {}, {  825000, } },
	{  691200, {}, {  837500, } },
	{  729600, {}, {  850000, } },
	{  768000, {}, {  862500, } },
	{  806400, {}, {  875000, } },
	{  840800, {}, {  887500, } },
	{  883200, {}, {  912500, } },
	{  921600, {}, {  925000, } },
	{  960000, {}, {  950000, } },
	{  998400, {}, {  962500, } },
	{ 1036800, {}, {  975000, } },
	{ 1074200, {}, { 1000000, } },
	{ 1113600, {}, { 1037500, } },
	{ 1152000, {}, { 1062500, } },
	{ 1190400, {}, { 1100000, } },
	{ 1228800, {}, { 1125000, } },
	{ 1267200, {}, { 1150000, } },
},
```
