### ISSUE TITLE
ram clocks on erista malfunctioning

### ISSUE THREAD

**Issue by 0DanDan0** [rashevskyv/4IFIR#25]
I have Samsung ram and I am running hos 16.1.0 keifir 4ifir 2.1 (couldn't find out how to do 1.9 beta) build every time I want to overclock my ram to 4ifir maximized it has a loud buzzing and almost looks like tv static and the only other two options are 204 mhz 4ifir optimized E and reverse nx rt (when i put it in docked reverse nx it doesn't affect anything) plz help

**Comment by rashevskyv** [comment]
This is just a guide. Give questions in tg group.

ср, 14 лют. 2024 р., 22:48 користувач 0DanDan0 ***@***.***>
пише:

**Comment by 0DanDan0** [comment]
i cannot use tg :/ also the ram goes to 1600 when on real dock

**Comment by rashevskyv** [comment]
Here is noone to help you. Sorry

ср, 14 лют. 2024 р., 22:53 користувач 0DanDan0 ***@***.***>
пише:

**Comment by 0DanDan0** [comment]
so to get help i need to go onto telegram

**Comment by rashevskyv** [comment]
This is just a guide. Nothing more

**Comment by 0DanDan0** [comment]
ok thx
