### ISSUE TITLE
1.6 Crush on Lite in boosted memory mode

### ISSUE THREAD

**Issue by kivarun** [rashevskyv/4IFIR#5]
After enabling memory boost on Switch Lite console starts to produce high strange noise screen stops to work. After reboot console is not booting - black screen after nintendo logo.
Steps to reproduce:
Boot console, type L+P+UP, go to 4IFIR Unreal. edit app profile, enable overclocking: CPU  - 4IFIR Optimized, GPU  4IFIR Optimized, Memory -  4IFIR Unrealized

**Comment by rashevskyv** [comment]
You should write to tg chat. There is unofficial guide and nothing more
