### ISSUE TITLE
make an uninstaller/easier way to uninstall

### ISSUE THREAD

**Issue by BuckinghamStudios** [rashevskyv/4IFIR#8]
I have no clue how to uninstall 4ifir and its messing with my system, i hear you have to have a backup or start from scratch in order to get rif of it but Im praying thats not the case. Can anyone help or direct me to a guide on how to fully uninstall 4ifir and revert the changes it made to my system? Thanks.

**Comment by rashevskyv** [comment]
This is AiO pack, so there is no way to uninstall it. You can move to another pack. Check instruction for clean installation for chosen pack
